### ISSUE TITLE
Docs for adding a custom field helper

### ISSUE THREAD

**Issue by Spone** [pantographe/view_component-form#126] opened 2023-02-02 20:34 UTC
Explain how to add a custom field helper to a custom FormBuilder (such as switch_box, image_field etc.)

**Comment by joelzwarrington** [comment] 2024-04-05 17:27
https://github.com/pantographe/view_component-form/issues/157 is a duplicate of this issue (or adding this documentation would resolve that issue).

It is my understanding that at a minimum, one can add a custom form field helper by adding their method to the builder:

```rb
def foo(method, options = {})
  render_component(:foo, @object_name, method, objectify_options(options))
end
```

and then

```rb
class Foo < ViewComponent::Form::FieldComponent # or ViewComponent::Form::BaseComponent
end
```

Then, if one would like further customization, they can add positional arguments.

```rb
def foo(method, arg_1, arg_2 = :some_default, options = {})
  render_component(:foo_with_positional_args, @object_name, method, arg_1, arg_2, objectify_options(options))
end
```

and then

```rb
class FooWithPositionalArgs < ViewComponent::Form::FieldComponent # or ViewComponent::Form::BaseComponent
  attr_reader :arg_1, :arg_2

  def initialize(form, object_name, method_name, arg_1, arg_2, options = {}) 
    @arg_1 = arg_1
    @arg_2 = arg_2

    super(form, object_name, method_name, options)
  end
end
```


Would you be open to me having a stab at this?

**Comment by Spone** [comment] 2024-04-05 18:42
Definitely! Thanks 🙏

**Closed** 2024-06-17 20:12 UTC
Labels: documentation
